# Generated by Django 2.0.4 on 2018-05-20 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20180506_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_time_date', models.DateField()),
                ('appoint_time_hour', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('appointee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('appointer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.MemberCard')),
            ],
            options={
                'ordering': ['-appoint_time_date', 'appoint_time_hour'],
            },
        ),
    ]
