# Generated by Django 2.0.4 on 2018-05-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180506_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutrecord',
            old_name='recharge_time',
            new_name='check_in_time',
        ),
    ]
